# Big Data Assignment — Reading Files, Cleaning, and Data Management
### Course: Algorithm Analysis (Gpo 104)
### Student: Kira Dayanna Espinoza Ortiz - A00841144

In [31]:
import pandas as pd
import numpy as np
## 1. Loading the Dataset
mis_datos = pd.read_csv("../data/cars.csv")
## Question 1. Review its structure

In [23]:
mis_datos.shape

(428, 15)

In [22]:
mis_datos.columns

Index(['Make', 'Model', 'Type', 'Origin', 'DriveTrain', 'MSRP', 'Invoice',
       'EngineSize', 'Cylinders', 'Horsepower', 'MPG_City', 'MPG_Highway',
       'Weight', 'Wheelbase', 'Length'],
      dtype='object')

In [ ]:
mis_datos.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
399,Toyota,Tundra Access Cab V6 SR5,Truck,Asia,All,25935,23520,3.4,6.0,190.0,14.0,17.0,4435.0,128.0,218.0
99,Chrysler,300M Special Edition 4dr,Sedan,USA,Front,33295,30884,3.5,6.0,255.0,18.0,27.0,3650.0,113.0,198.0
330,Porsche,Cayenne S,SUV,Europe,All,56665,49865,4.5,8.0,340.0,14.0,18.0,NaN,112.0,188.0
373,Toyota,Prius 4dr (gas/electric),Hybrid,Asia,Front,20510,18926,1.5,4.0,110.0,59.0,51.0,2890.0,106.0,175.0
69,Chevrolet,Cavalier 2dr,Sedan,USA,Front,14610,13697,2.2,4.0,140.0,26.0,37.0,2617.0,104.0,183.0

In [27]:
mis_datos.tail()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

In [28]:
mis_datos.sample(5)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
160,Honda,Civic Si 2dr hatch,Sedan,Asia,Front,19490,17849,2.0,4.0,160.0,26.0,30.0,2782.0,101.0,166.0
253,Mercedes-Benz,C230 Sport 2dr,Sedan,Europe,Rear,26060,24249,1.8,4.0,189.0,22.0,30.0,3250.0,107.0,178.0
112,Dodge,Caravan SE,Sedan,USA,Front,21795,20508,2.4,4.0,150.0,20.0,26.0,3862.0,113.0,189.0
381,Toyota,Corolla LE 4dr,Sedan,Asia,Front,15295,13889,1.8,4.0,130.0,32.0,40.0,2524.0,102.0,178.0
416,Volvo,XC90 T6,SUV,Europe,All,41250,38851,2.9,6.0,268.0,15.0,20.0,4638.0,113.0,189.0

In [24]:
mis_datos.dtypes

Make            object
Model           object
Type            object
Origin          object
DriveTrain      object
MSRP             int64
Invoice          int64
EngineSize     float64
Cylinders      float64
Horsepower     float64
MPG_City       float64
MPG_Highway    float64
Weight         float64
Wheelbase      float64
Length         float64
dtype: object

In [26]:
mis_datos.describe()

,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
count,428.000000,428.000000,425.000000,425.000000,423.000000,426.000000,426.000000,423.000000,426.000000,427.000000
mean,32774.855140,30014.700935,3.195294,5.811765,215.576832,20.065728,26.840376,3578.229314,108.166667,186.381733
std,19431.716674,17642.117750,1.111932,1.557802,71.978098,5.249574,5.749505,759.034549,8.327582,14.369110
min,10280.000000,9875.000000,1.300000,3.000000,73.000000,10.000000,12.000000,1850.000000,89.000000,143.000000
25%,20334.250000,18866.000000,2.300000,4.000000,165.000000,17.000000,24.000000,3103.000000,103.000000,178.000000
50%,27635.000000,25294.500000,3.000000,6.000000,210.000000,19.000000,26.000000,3476.000000,107.000000,187.000000
75%,39205.000000,35710.250000,3.900000,6.000000,252.500000,21.750000,29.000000,3978.500000,112.000000,194.000000
max,192465.000000,173560.000000,8.300000,12.000000,500.000000,60.000000,66.000000,7190.000000,144.000000,238.000000

In [30]:
mis_datos.describe(include="all")

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
count,428,428,428,428,428,428.000000,428.000000,425.000000,425.000000,423.000000,426.000000,426.000000,423.000000,426.000000,427.000000
unique,38,425,6,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Toyota,G35 4dr,Sedan,Asia,Front,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,28,2,262,158,226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,32774.855140,30014.700935,3.195294,5.811765,215.576832,20.065728,26.840376,3578.229314,108.166667,186.381733
std,NaN,NaN,NaN,NaN,NaN,19431.716674,17642.117750,1.111932,1.557802,71.978098,5.249574,5.749505,759.034549,8.327582,14.369110
min,NaN,NaN,NaN,NaN,NaN,10280.000000,9875.000000,1.300000,3.000000,73.000000,10.000000,12.000000,1850.000000,89.000000,143.000000
25%,NaN,NaN,NaN,NaN,NaN,20334.250000,18866.000000,2.300000,4.000000,165.000000,17.000000,24.000000,3103.000000,103.000000,178.000000
50%,NaN,NaN,NaN,NaN,NaN,27635.000000,25294.500000,3.000000,6.000000,210.000000,19.000000,26.000000,3476.000000,107.000000,187.000000
75%,NaN,NaN,NaN,NaN,NaN,39205.000000,35710.250000,3.900000,6.000000,252.500000,21.750000,29.000000,3978.500000,112.000000,194.000000
max,NaN,NaN,NaN,NaN,NaN,192465.000000,173560.000000,8.300000,12.000000,500.000000,60.000000,66.000000,7190.000000,144.000000,238.000000